### ISSUE TITLE
CI: Docker-based tests failing due to oldest-supported-numpy

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#107]
It appears that we are now running into issues trying to install `oldest-supported-numpy` in our GDAL docker test containers.

See: https://github.com/geopandas/pyogrio/runs/6455834609?check_suite_focus=true#step:5:27

**Comment by brendan-ward** [comment]
Related: https://github.com/scipy/oldest-supported-numpy/issues/53

**Comment by jorisvandenbossche** [comment]
I ran into a similar error in shapely: https://github.com/shapely/shapely/pull/1388
