### ISSUE TITLE
Add API for reading bounding boxes of features

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#12]
Use [OGR_G_GetEnvelope](https://gdal.org/api/vector_c_api.html#_CPPv417OGR_G_GetEnvelope12OGRGeometryHP11OGREnvelope)
(and possibly 3D variant) to read the bounding box of each feature into 4 columns: xmin, ymin, xmax, ymax.

Goal is to assist determining partitions and spatial indexes of very large datasets without reading all records and geometries into memory, to support projects like [dask-geopandas](https://github.com/geopandas/dask-geopandas).

To be determined:
* add this as a parameter to `read_dataframe()`: `read_bounds`, if `True` will add 4 additional columns to the fields read from the features.  Downsides: possible (though unlikely) name collision of xmin...ymax fields with existing field names in the dataset, and ambiguity around which fields are native to the dataset vs derived.
* create a new function in Cython and expose in Python: `read_bounds()` which will return an ndarray of shape (4, n) or (n, 4), and accept similar parameters as `read_dataframe()` for filtering and subsetting records.

Currently leaning toward the latter option as it will likely be more performant and easier to use downstream.

/cc @jorisvandenbossche @martinfleis @tastatham

**Comment by martinfleis** [comment]
I also like the second option. Feels much cleaner also.

**Comment by brendan-ward** [comment]
This also needs to return an ndarray of FIDs to provide global IDs that can be used to later read out specific features after partitioning (see #13).

**Comment by jorisvandenbossche** [comment]
Yes, I think a separate function (second option) is also important to easily *only* read the bounds / ids (you don't want to read/convert the full geometry and field attributes in that case)
