### ISSUE TITLE
Include layer bounds in read_info

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#15]
Use [OGR_L_GetExtent](https://gdal.org/api/vector_c_api.html#_CPPv415OGR_L_GetExtent9OGRLayerHP11OGREnvelopei)

to get the extent of a layer and include via read_info.

Might need to make this a keyword parameter, since some data sources use expensive calculations to determine this.

TODO: check if any of the supported drivers require the expensive variant of this calculation.

**Comment by theroggy** [comment]
A new issue was opended for this: #274.

Because there is more info there now then here, I'll close this older one.
