### ISSUE TITLE
QST: warning when read results in 0 rows from file needed?

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#152]
Not important... but just wondering... 

Because I recently changed the I/O used from geopandas/fiona to pyogrio in [geofileops](https://github.com/geofileops/geofileops), I noticed (alongside the spatial filter issue for gpkg) that pyogrio throws a warning when a layer is read and no data is returned.
I can easily capture and ignore this obviously, but I wondered if a warning is warented because at first sight is seems quite default/normal behaviour that when you read from a datasource (especially with a filter) that you can retrieve 0 rows. 

If getting 0 rows as a result is unwanted behiour it is also easy to check the result for it (and probably you wouldn't use the warning for that anyway).

**Comment by martinfleis** [comment]
I think it is useful because it is generally an unexpected results. If you knew it is empty you wouldn't read it.

**Comment by theroggy** [comment]
Indeed, for reading an entire file this is probably most of the time unexpected. 

I was thinking about a case where I am not reading the entire file but rather reading it with a filter... and then it is often normal that you don't get any results. But possibly this is indeed a less common case than reading the entire file...

**Comment by brendan-ward** [comment]
Raising a warning when there are no filters and there are no records to read, and not raising a warning when there are any filters seems reasonable to me.

**Comment by theroggy** [comment]
Has become a duplicate because of #294
