### ISSUE TITLE
ENH: avoid I/O when columns don't need to be returned 

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#153]
I noticed in the code that all columns are always read by ogr, but that they are not copied in the result by pyogrio.

Using [OGR_L_SetIgnoredFields](https://gdal.org/doxygen/ogr__api_8h.html#a6d43f1474201356bed2e6f92e7d37154) could/should improve read spead because it enables GDAL to avoid reading the data.

**Comment by jorisvandenbossche** [comment]
For reference, I added this to https://github.com/geopandas/pyogrio/pull/155/ (https://github.com/geopandas/pyogrio/pull/155/commits/eb5943dfc680599b3add55b1e72228fd037d37b4), which could be used as starting point for doing this for the normal readers as well
