### ISSUE TITLE
Missing GEOS on MacOS / Linux release test instances breaks bbox tests

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#162]
Side effect of #150 ; GDAL returns different results for a bbox filter when GEOS is available on the system.

All our main CI test instances have GEOS available, but we don't install additional binary dependencies on the wheel test instances (GDAL is packaged in the wheel but not GEOS).

I think we have 3 options:
- ensure that GEOS is available on the wheel test instance
- parameterize (or skip) the bbox tests to expect different behavior when GEOS is not available (`pyogrio.__gdal_geos_version__ is None`)
- adjust the bounds used for testing to avoid cases where bounding boxes overlap but geometries to not (leaning toward this option)

**Comment by jorisvandenbossche** [comment]
>  but we don't install additional binary dependencies on the wheel test instances (GDAL is packaged in the wheel but not GEOS).

GEOS is actually included in the wheels, but the GDAL library for some reason thinks it's not available -> https://github.com/geopandas/pyogrio/issues/92 (the practical outcome is the same of course, the wheels run GDAL without GEOS on MacOS/Linux)

> I think we have 3 options:

Maybe keeping _some_ tests where we check the expected result depending on whether `pyogrio.__gdal_geos_version__ is None` might still be useful?
