### ISSUE TITLE
pyogrio.__version__ includes "v"

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/pyogrio#208]
```
>>> pyogrio.__version__
'v0.5.0'
```

I don't think it matters that much (if you use something like packaging.version.Version for version comparisons, that should deal with that), but most other libraries I know drop the "v" at runtime.

**Comment by jorisvandenbossche** [comment]
I suppose it is here:

https://github.com/geopandas/pyogrio/blob/d8ea90315d7a7922bb07b249804aefbc8409f39c/pyogrio/_version.py#L43

while in pandas that is "v" (https://github.com/geopandas/geopandas/blob/7e1164fff8d85ef48f857c10a648188b3692b56e/geopandas/_version.py#L46)

**Comment by martinfleis** [comment]
No, it should be here https://github.com/geopandas/pyogrio/blob/d8ea90315d7a7922bb07b249804aefbc8409f39c/setup.cfg#L6 . _version.py is generated and shall not be manually edited.

**Comment by brendan-ward** [comment]
I noticed we're not setting `parentdir_prefix` but geoapandas and shapely are.  I tried with and without and it had no effect locally, but if I'm reading the docs correctly that is only used to resolve it from a folder (e.g., when building tarballs).  Should we set this, just in case?

**Comment by jorisvandenbossche** [comment]
Yes, Brendan alraedy made a PR: https://github.com/geopandas/pyogrio/pull/210

**Comment by jorisvandenbossche** [comment]
Yeah, I don't really understand what the `parentdir_prefix` is meant to do .. Also pandas does that. Maybe just do the same to be sure?
