### ISSUE TITLE
ENH: support URI schemes like zip:// (in addition to GDAL's vsi)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/pyogrio#21]
Currently reading a file like the following fails (file path is the output of `geopandas.datasets.get_path("nybb")`):

```
In [8]: pyogrio.read_dataframe('zip:///home/joris/scipy/geopandas/geopandas/datasets/nybb_16a.zip')
...
DriverError: zip:///home/joris/scipy/geopandas/geopandas/datasets/nybb_16a.zip: No such file or directory
```

but using GDAL's native vsi pattern works:

```
In [10]: pyogrio.read_dataframe('/vsizip//home/joris/scipy/geopandas/geopandas/datasets/nybb_16a.zip')
Out[10]: 
   BoroCode       BoroName     Shape_Leng    Shape_Area                                           geometry
0         5  Staten Island  330470.010332  1.623820e+09  MULTIPOLYGON (((970217.022 145643.332, 970227....
1         4         Queens  896344.047763  3.045213e+09  MULTIPOLYGON (((1029606.077 156073.814, 102957...
2         3       Brooklyn  741080.523166  1.937479e+09  MULTIPOLYGON (((1021176.479 151374.797, 102100...
3         1      Manhattan  359299.096471  6.364715e+08  MULTIPOLYGON (((981219.056 188655.316, 980940....
4         2          Bronx  464392.991824  1.186925e+09  MULTIPOLYGON (((1012821.806 229228.265, 101278...

```

Given that those VSI paths are quite uncommon for general users, I think it would be nice to support the more general URI schemes as well. 
In Fiona this is handled by their `path` module: https://github.com/Toblerity/Fiona/blob/885dbd11c5dcb2c61862faefc28bfbbff99954de/fiona/path.py

**Comment by jorisvandenbossche** [comment]
(automatically detecting a zip file would also be nice, but that's a separate feature request)

**Comment by jamesmyatt** [comment]
Would be good to implement fsspec support for general URIs.

**Comment by jorisvandenbossche** [comment]
@jamesmyatt yes indeed! I was actually looking at that as well, and the main issue there is to allow reading from byte blobs / file like object (instead of just string paths). This is not yet implemented I think, and was writing an issue for that. 

I think it is still good to use GDAL for those types it supports, but have fsspec available as the general solution (either included in pyogrio, or either explicitly used by the user, which is to be discussed)

**Comment by jamesmyatt** [comment]
@jorisvandenbossche #22 would be great. Then I think fsspec could be implemented cheaply. But you probably already know about that from pandas.

I did wonder how it does the file IO under-the-hood. Is it just handled by GDAL? Does that make it hard to insert fsspec in between (or something else like cloudpathlib)?

**Comment by jorisvandenbossche** [comment]
GDAL supports quite some virtual file systems (compressed files, cloud files) out of the box, see https://gdal.org/user/virtual_file_systems.html

It doesn't make it harder to use fsspec in combination with gdal (since it also supports "virtual file handle" that could wrap fsspec OpenFile objects, or read from bytes once we have #22), but it does bring up the API design question: what gets used by default, or how to choose between both options?

**Comment by jorisvandenbossche** [comment]
@brendan-ward what are your thoughts on this one? Basically we need the functionality of Fiona's `path` module (https://github.com/Toblerity/Fiona/blob/master/fiona/path.py) to detect URIs and convert them to a vsi path like

```
>>> vsi_path(parse_path("zip+s3://fiona-testing/coutwildrnp.zip"))
'/vsizip/vsis3/fiona-testing/coutwildrnp.zip'
```

I think of two options: copy the fiona code verbatim (so it's easy to keep in sync in case it would get updated / bug fixes) and use as is, or implement a simplified / slimmed down version of it with just what we need (I _think_ we don't need the classes)

**Comment by brendan-ward** [comment]
I think my preference would be to use a slimmed down, functional variant (strings in, strings out) of Fiona's approach, if we don't need the classes (agreed that it doesn't seem like we need them).
