### ISSUE TITLE
ENH: add support for metadata tags if supported by driver

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#218]
Allow passing in tags as a dict to `write()` / `write_dataframe()`, similar to [Fiona #821](https://github.com/Toblerity/Fiona/pull/821)

To support [GeoPandas #2777](https://github.com/geopandas/geopandas/issues/2777)

**Comment by jorisvandenbossche** [comment]
Fiona/rasterio set the example of calling this "tags", but personally I would find the "metadata" term that GDAL uses clearer.
