### ISSUE TITLE
ENH: add automatic detection of 2.5D in write_dataframe

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#222]
At the moment write_dataframe doesn't take in account whether the input is 3D or not while determining the geometry_type.

The has_z property should be used to determine this...

Noticed in the context of this PR: [geopandas #2829](https://github.com/geopandas/geopandas/pull/2829)

**Comment by jorisvandenbossche** [comment]
We should probably check how GDAL handles mixed dimensions (e.g. if you have a Point and PointZ, and we specify `wkbPoint25D` as geometry type to GDAL, will that work? i.e. would a `has_z().any()` check work OK?)

**Comment by jorisvandenbossche** [comment]
So it seems we already have basic support for it (https://github.com/geopandas/pyogrio/commit/8679f3e2a07b62940b8bd9f55d1b4c690acc76ef), if you specify the geometry_type manually. So indeed (as your title actually already said ;)), it's the automatic detection part that is missing.

**Comment by jorisvandenbossche** [comment]
And I missed you already opened a PR ;)

**Comment by theroggy** [comment]
> We should probably check how GDAL handles mixed dimensions (e.g. if you have a Point and PointZ, and we specify `wkbPoint25D` as geometry type to GDAL, will that work? i.e. would a `has_z().any()` check work OK?)

Mixing 2D and 25D while using 25D geometry_type seems to be working for all file types except flatgeobuffer... But flatgeobuffer also has an issue when 2D and 25D is mixed and a 2D geometry_type is used...

**Comment by brendan-ward** [comment]
Unlike the case of auto-promoting mixed singular and multiple geometries for output to flatgeobuf, I'm less keen on automatically making all coordinates 3D (presumably filled with `nan`).  I think letting it error when writing to a driver that doesn't support mixed dimensionality seems reasonable.

**Comment by jorisvandenbossche** [comment]
Do you get a sensible error from GDAL in the case of flatgeobuffer? (and mixed dimensions) 
If so, the has_z.any() logic might be fine, and the users get the error if that doesn't work.

**Comment by theroggy** [comment]
> Do you get a sensible error from GDAL in the case of flatgeobuffer? (and mixed dimensions) If so, the has_z.any() logic might be fine, and the users get the error if that doesn't work.

It's sensible if you know what it is about... not sure if it's clear when you get it out of the blue:
`'Could not add feature to layer at index 1: ICreateFeature: Mismatched geometry type'`
