### ISSUE TITLE
Register package on PyPI

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/pyogrio#26]
@brendan-ward I know the README indicates that the package is not yet on PyPI because we don't have wheels yet, but I think it would be good to already register it anyway (source sdist only for now). Eg to avoid that other people take the name.

**Comment by brendan-ward** [comment]
That's a great idea; source sdist seems reasonable.  Do you want to go ahead and do that?

**Comment by jorisvandenbossche** [comment]
I am happy to do so, and can add you as a co-admin (do you have a PyPI user name?)

**Comment by brendan-ward** [comment]
`bcward` on PyPI.  Thanks!

**Comment by jorisvandenbossche** [comment]
Done! -> https://pypi.org/project/pyogrio/

We might want to cut a new release (maybe after the FID PR is merged?), since this one is already a few months old. We might also want to remove the generated C files from the sdist (since cython is already a build dependency)

**Comment by martinfleis** [comment]
> We might want to cut a new release (maybe after the FID PR is merged?)

Let me finish the docs over the weekend, to have a complete package.
