### ISSUE TITLE
Use Arrow pandas types by default when `use_arrow=True`?

### ISSUE THREAD

**Issue by kylebarron** [geopandas/pyogrio#303]
> One question here is whether we want to set pandas to use the arrow types by default when `use_arrow` is True? In that case, since the data starts as arrow it would speed up the pandas conversion considerably

Thoughts either way? (I figured for visibility this should be its own issue)

_Originally posted by @kylebarron in https://github.com/geopandas/pyogrio/issues/241#issuecomment-1741795111_

**Comment by jorisvandenbossche** [comment]
My general stance is that we should follow the default data types as in pandas. And at the moment, the arrow dtypes are not the default in pandas, and so we should also not make them the default. 

We could document better how you can easily obtain that yourself, though, now we have the keyword from https://github.com/geopandas/pyogrio/pull/273
