### ISSUE TITLE
Drop support for Python 3.6 (and 3.7?)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/pyogrio#31]
I think most packages in the ecosystem have already dropped Python 3.6, and several also already dropped 3.7 (eg pandas dropped 3.7 in the just released 1.4 release, and also numpy dropped it in 1.22)

Shapely (pygeos) will also at least require 3.7+

https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by martinfleis** [comment]
I guess that with pyogrio, we don't need to be super backward compatible, so I'd be fine supporting 3.8+.

**Comment by brendan-ward** [comment]
Agreed.  We're only testing on 3.8 due to Docker GDAL python versions, so mostly this would involve changing the README.

Does this also need a change in the pyogrio-feedstock to limit Python versions?

**Comment by jorisvandenbossche** [comment]
> We're only testing on 3.8 due to Docker GDAL python versions

We should probably try to install a more recent python version in some of those dockers, so we also test with python 3.9 / python 3.10?

> Does this also need a change in the pyogrio-feedstock to limit Python versions?

Yes, that can be done on the next release (conda-forge already dropped Python 3.6 packages a while ago, but for 3.7 we should add an explicit skip, see eg how numpy does this: https://github.com/conda-forge/numpy-feedstock/blob/5525fb0236102bdfab01fe0ccacd8551265ea4c6/recipe/meta.yaml#L23)

**Comment by jorisvandenbossche** [comment]
Actually, it seems we already skip for <3.8 on the conda recipe: https://github.com/conda-forge/pyogrio-feedstock/blob/689cc7942408de13d38ea4dc7d08215c074f2b45/recipe/meta.yaml#L14

**Comment by EwoutH** [comment]
Since this is already over two years ago, is it time to drop the next two Python versions?

[SPEC 0](https://scientific-python.org/specs/spec-0000/), which is the successor of [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), suggests so. Packages like NumPy and Pandas also have done so already.
