### ISSUE TITLE
Support for forcing driver in `read_dataframe`

### ISSUE THREAD

**Issue by kylebarron** [geopandas/pyogrio#310]
I have some CSV data that uses a file extension that is not `.csv`. It appears that the OGR CSV driver only auto-detects CSV data if the extension is `.csv`. Is there a way to force the use of a specific driver when not auto-detected? It appears there is not already. This would be akin to [`driver` in `fiona.open`](https://fiona.readthedocs.io/en/stable/fiona.html#fiona.open).

**Comment by brendan-ward** [comment]
It looks like Fiona uses the `enabled_drivers` to restrict the drivers that are checked by GDAL when opening a file for reading (not `driver`, which is used for writing).  It is unclear from the example in the docstring if it actually allows overriding the driver used to open the file, or if it simply constraints the set of drivers checked - which would still depend on file extension.

In pyogrio we have it enable all drivers at startup; I'm not sure we want to selectively enable some of them.

The GDAL Python bindings let you first obtain [a driver instance and then use that to open a path](https://gdal.org/api/python/osgeo.ogr.html#osgeo.ogr.Driver.Open), so it may provide a better example to check.

**Comment by theroggy** [comment]
Have you tried this, from the [GDAL CSV driver documentation](https://gdal.org/drivers/vector/csv.html)?

> For files structured as CSV, but not ending with .CSV extension, the 'CSV:' prefix can be added before the filename to force loading by the CSV driver.

**Comment by kylebarron** [comment]
Ooo... the driver documentation page is very long and I missed that. But yes that does work!

I'm happy to close this or keep it open in case forcing a driver is useful in other cases

**Comment by brendan-ward** [comment]
We can close until there is an urgent need to add that capability for other drivers.

**Comment by theroggy** [comment]
This works for all drivers already... the prefix to use is defined with the GDAL_DMD_CONNECTION_PREFIX metadata item of each driver, e.g.:
```
poDriver->SetMetadataItem(GDAL_DMD_CONNECTION_PREFIX, "MSSQL:");
```
