### ISSUE TITLE
ENH: Support writing using the Arrow API

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#314]
GDAL recently introduced support for writing files using the Arrow interface in [GDAL #8517](https://github.com/OSGeo/gdal/pull/8517).

**Comment by kylebarron** [comment]
GDAL 3.8.0 is out! https://github.com/OSGeo/gdal/releases/tag/v3.8.0

**Comment by kylebarron** [comment]
If no one else is interested in taking this, I may give a shot at this before 0.8. At the current release cadence I'd like to get this into 0.8 instead of 0.9.
