### ISSUE TITLE
MNT: Update Github actions for Release

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#317]
See warnings emitted at: https://github.com/geopandas/pyogrio/actions/runs/6644743658

**Comment by martinfleis** [comment]
It seems to be just a question of pointing the actions to the latest released versions.

**Comment by brendan-ward** [comment]
See instructions for updating pypi action to trusted publishing instead of tokens at: https://github.com/marketplace/actions/pypi-publish#trusted-publishing
