### ISSUE TITLE
TST: Test Python 3.9 and 3.10 on CI

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#36]
Per #31, we need to start testing 3.9 and 3.10 via Github Actions.

**Comment by martinfleis** [comment]
Do we need to rely on those GDAL containers? Would standard conda env as we have elsewhere be enough? It could make the maintenance a bit easier.

**Comment by brendan-ward** [comment]
I think we could certainly add in conda env for testing.  Probably also a good idea to keep around at least one test using the GDAL containers.  I can work on adding in Conda based tests.
