### ISSUE TITLE
When geopandas is available, pyogrio expects pyproj to be available

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#456]
Since geopandas 1.0, geopandas-base doesn't imply anymore that pyproj will be installed as well.

But, pyogrio now expects it to be.

Noticed in #452.

**Comment by jorisvandenbossche** [comment]
Good point, we should update our importing of pyproj and provide a better error message if it is not available.

**Comment by jorisvandenbossche** [comment]
Although https://github.com/geopandas/pyogrio/pull/452 already updates the one place where we import pyproj?

**Comment by theroggy** [comment]
Yes, after making this issue I noticed it was easy to just remove the import...

**Comment by theroggy** [comment]
Back to the drawing board... I added pyproj previously to the environment file to focus the test on the switch to `libgdal-core` and hadn't removed it yet. Now I removed it again in #452 quite some tests are failing because `pyproj` not being available leads to different behaviour in geopandas...

**Comment by martinfleis** [comment]
When we allowed geopandas without pyproj, we had to change quite a lot of tests as the expected value for CRS changes to None. 

If we want to properly do it here, we might need to follow the same model. 

We should allow pyogrio without pyproj to support this model in geopandas so I wouldn't add it necessarily as a conda dependency.

**Comment by theroggy** [comment]
The tests that failed when `pyproj` was not available anymore in #452 pass again...
