### ISSUE TITLE
BUG: failure during parsing GDAL version number on windows during setup

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#500]
Per our latest CI failures with conda-forge on Windows:

```Python
...setuptools\build_meta.py", line 320, in run_setup
      exec(code, locals())
    File "<string>", line 156, in <module>
    File "<string>", line 156, in <genexpr>
  ValueError: invalid literal for int() with base 10: ''
  [end of output]
```

If I follow, it is failing on line 156 of `setup.py`:

```Python
gdal_version = tuple(int(i) for i in gdal_version_str.strip("dev").split("."))
```

The GDAL version in conda-forge used here looks valid, so I'm not yet sure why this is failing to parse.

**Comment by brendan-ward** [comment]
The issue is that for the Windows conda test runner we are setting the version via an environment variable that doesn't account for the longer version number of 3.10.x:

```
GDAL_VERSION=$(gdalinfo --version | cut -c 6-10)
```

This returns "3.10.", which then fails to parse.

**Comment by jorisvandenbossche** [comment]
Ah, good catch!
