### ISSUE TITLE
BUG: support writing None geometries (for geopackage files)

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#59]
At least in geopackages, it is valid to have NULL/None geometries in a layer.

However, when writing a `GeoDataFrame` with a `None` geometry this throws an error. Depending if the `None` geometry is first in the `GeoDataframe` or not triggers another error.

The following code triggers the errors:
```
import geopandas as gpd
import pyogrio
import shapely.geometry

# This results in ValueError: geometry_type must be provided
output_path = r"C:\temp\test_none_geom.gpkg"
test_gdf = gpd.GeoDataFrame(
        geometry=[
                None,
                shapely.geometry.Polygon(shell=[(1, 1), (1, 2), (2, 2), (2, 1), (1, 1)])],
        crs="epsg:31370")
pyogrio.write_dataframe(test_gdf, output_path)

# This results in TypeError: cannot convert 'NoneType' object to bytearray
test_gdf = gpd.GeoDataFrame(
        geometry=[
                shapely.geometry.Polygon(shell=[(1, 1), (1, 2), (2, 2), (2, 1), (1, 1)]),
                None],
        crs="epsg:31370")
pyogrio.write_dataframe(test_gdf, output_path)
```

**Comment by brendan-ward** [comment]
We took a fairly strict view when building this out  that geometries must always be present, and didn't add adequate handling for when they aren't.  I'm assuming that GDAL/OGR can handle NULL geometries provided we construct things that way, so we should allow this - and allow GDAL/OGR to be the gatekeeper if those aren't valid for a particular data format.

**Comment by theroggy** [comment]
reference #105
