### ISSUE TITLE
CI: Missing GEOS in wheel builds for Linux / MacOS

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#92]
As [detected](https://github.com/geopandas/pyogrio/issues/86#issuecomment-1111911959) in fixes under #86, GEOS is not getting correcly compiled into GDAL by vcpkg for Linux / MacOS, but is getting correctly compiled into GDAL on Windows.

**Comment by jorisvandenbossche** [comment]
This has been fixed by  #161
